blog/apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'
urlpatterns = [    
    path('', views.Listar_Noticias, name = 'listar'),

    path('Detalle/<int:pk>', views.Detalle_Noticias, name = 'detalle'),

    path('Comentario/', views.Comentar_Noticia, name = 'comentar'),
    
]

blog/apps/usuarios/urls.py
from django.urls import path

from . import views

# LA URL EMPIEZA CON Noticias/ <este archivo>

app_name = 'usuarios'

urlpatterns = [
    
    path('registro/', views.Registro.as_view(), name = 'registro'),

   

]

blog/blog/urls.py
from django.contrib import admin

from django.urls import path, include

from . import views

from django.contrib.auth import views as auth

from django.conf import settings

from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.Home, name = 'home'),
    
    path('Nosotros/', views.Nosotros, name = 'nosotros'),
    
    path('Noticias/', include('apps.noticias.urls')),

    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    
    path('logout/',auth.LogoutView.as_view(), name="logout"),
    
    path('Usuario/',include('apps.usuarios.urls')),
    
    path('Contacto/', views.Contacto, name = 'contacto'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/apps/noticias/models.py
from django.db import models
from apps.usuarios.models import Usuario


class Categoria(models.Model):
    nombre = models.CharField(max_length = 60)

    def __str__(self):
        return self.nombre

class Noticia(models.Model):
    titulo = models.CharField(max_length = 150)
    cuerpo = models.TextField()
    imagen = models.ImageField(upload_to='noticias')
    categoria_noticia = models.ForeignKey(Categoria, on_delete = models.CASCADE)
    fecha = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.titulo

class Comentario(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    texto = models.TextField(max_length=1500)
    noticia = models.ForeignKey(Noticia, on_delete= models.CASCADE)
    fecha = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return (f"{self.noticia}-->{self.texto}")

blog/apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    pass

blog/apps/usuarios/forms.py
from django import forms


from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class RegistroForm(UserCreationForm):
	email = forms.EmailField(label='Correo', required=True)
	first_name = forms.CharField(label='Nombre', required=True)
	last_name = forms.CharField(label='Apellido', required=True)
	password1 = forms.CharField(
		label='Contraseña', widget=forms.PasswordInput, required=True)
	password2 = forms.CharField(
		label='Confirmar Contraseña', widget=forms.PasswordInput, required=True)

	class Meta:
		model = Usuario
		fields = [
			'first_name',
			'last_name',
			'username',
			'email',
			'password1',
			'password2'
		]
	def __init__(self,*args,**kwargs):
		super(RegistroForm, self).__init__(*args, **kwargs)
		self.fields["username"].help_text = None

blog/apps/noticias/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Noticia, Categoria, Comentario
from django.urls import reverse_lazy


def Listar_Noticias(request):
    contexto = {}

    id_categoria = request.GET.get('id', None)

    if id_categoria:
        n = Noticia.objects.filter(categoria_noticia = id_categoria)
    else:
        n = Noticia.objects.all().order_by('-fecha')

    contexto['noticias'] = n

    cat = Categoria.objects.all().order_by('nombre')
    contexto['categorias'] = cat
    
    return render(request, 'noticias/listar.html', contexto)

    
def Detalle_Noticias(request,pk):
    contexto = {}
    n = Noticia.objects.get(pk = pk) #RETORNA SOLO UN OBJETO
    contexto['noticia'] = n

    c = Comentario.objects.filter(noticia= n)

    contexto['comentarios'] = c
    

    return render(request, "noticias/detalle.html", contexto)

@login_required
def Comentar_Noticia(request):
    com = request.POST.get('comentario', None)
    usu = request.user
    noti = request.POST.get('id_noticia', None)#obtengo la pk
    noticia = Noticia.objects.get(pk=noti)#busco la noticia con esa pk
    coment = Comentario.objects.create(usuario=usu, noticia= noticia, texto=com)

    return redirect(reverse_lazy('noticias:detalle', kwargs={'pk':noti}))

blog/apps/usuarios/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import RegistroForm
# Create your views here.



class Registro(CreateView):
	#FORMULARIO DJANGO
	form_class = RegistroForm
	success_url = reverse_lazy('login')
	template_name = 'usuarios/registro.html'

blog/blog/views.py
from django.shortcuts import render

def Home(request):

	return render(request, 't_home.html')

def Nosotros(request):
    return render(request, 't_nosotros.html')

def Contacto(request):
    return render(request, 't_contacto.html')

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
    <title> Amigos del Arte | {% block titulo %}{% endblock titulo %}</title>
    <link rel="shortcut icon" href="{% static 'img/logo2.png' %}"/>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    
    <!-- Fuente UBUNTU -->
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
    
    <!-- Fuente ROBOTO -->
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&family=Ubuntu&display=swap" rel="stylesheet">

    <!-- Fuente UNBOUNDED -->
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@600&display=swap" rel="stylesheet">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'img/main.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
</head>


<body>
    <header>
        <div class="head">

            <div class="logo">
                <a title="logo_fundacion" href="{% url 'home' %}"><img src="{% static 'img/logo_largo_color.png' %}" alt="logo_fundacion"></a>
            </div>

            <nav class="navbar">
                <a href="{% url 'home' %}">Inicio</a>
                <a href="{% url 'nosotros' %}">Nosotros</a>
                <a href="{% url 'noticias:listar' %}">Noticias</a>
                <a href="{% url 'contacto' %}">Contacto</a>

                {% if user.is_authenticated %}
                    <strong class"mensaje">Bienvenido {{user.username}}</strong>
                    <a href="{% url 'logout' %}">CERRAR SESION</a>
                {% else %}
                    <a href="{% url 'login' %}">INICIAR SESION</a>
                    <a href="{% url 'usuarios:registro' %}">Registrar</a>

                {% endif %}
            </nav>
        
        </div>     
    </header>
    {% block contenido %}    {% endblock contenido %}
</body> 

<footer>
    Página creada y modificada por alumnos de la COM.1/G6 del INFORMATORIO
</footer>


</html>

blog/templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} NOTICIAS {% endblock titulo %}

{% block contenido %}

<h1 class="title">noticias</h1>

<section class="detalle-noticia">

  	<h2 class="integrante">{{noticia.titulo}}</h2>
  
  	<img src="{{noticia.imagen.url}}" width="600px" height="auto" class="img-detalle">
  	<div class="hora-categ">

		  <h6>{{noticia.fecha}}</h6>
		  <h6>CATEGORIA: {{noticia.categoria_noticia}}</h6>
	</div>
  <p>{{noticia.cuerpo}}</p>
</section>


	<a href="{% url 'noticias:listar' %}" class="boton-volver">VOLVER A NOTICIAS</a>
	
	<section class="comentar">
		
		<form method="POST" action="{% url 'noticias:comentar' %}" class="comentarios">{% csrf_token %}
			<textarea  name="comentario" maxlength="1500" placeholder="Deje su comentario aquí"></textarea>
			<input type="text" name="id_noticia" value="{{noticia.pk}}" hidden="">
			<input type="submit" value="ENVIAR" class="guardar">
		</form>
	</section>
	<br>
	<br>
	<section class="respuestas">
		
		<h3 class="integrante">COMENTARIOS</h3>
		
		
		{% for com in comentarios %}
		<p>{{com.texto}}</p>
		{% if user == com.usuario %}
		<!--  <a href="" class="borrar">borrar</a>  -->
		{% endif %}
		<strong class="fecha-comentario">{{com.fecha}}</strong><br>
		<strong class="usuario-comentario">{{com.usuario}}</strong><br>
		
		
		{% endfor %}
	</section>
	
{% endblock contenido %}
	

blog/templates/noticias/listar.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} NOTICIAS {% endblock titulo %}

{% block contenido %}

<h1 class="title">noticias</h1>
<div class="fondo-submenu">
  <div class="navbar">
    <a href="{% url 'noticias:listar' %}">Noticias</a>
    {% for cat in categorias %}
    <a href="?id={{cat.pk}}">{{cat.nombre}}</a>
    {% endfor %}
  </div>
</div>
<main class="main">
  
  <section class="principal">
    
    <section class="noticias">
      {% for noti in noticias %}
      <article class="post">
        <img src="{{noti.imagen.url}}" width="300px" height="auto" class="img-noticia">
        <p><a href="{% url 'noticias:detalle' noti.pk %}" class="titulos-noticias">{{noti.titulo}}</a></p>
        <!--
          <p>FECHA: {{noti.fecha}}</p>
          <p>CATEGORIA: {{noti.categoria_noticia}}</p>
          <p>CUERPO: {{noti.cuerpo}}</p>
        -->
      </article>
      {% endfor %}
    </section>
  </section>
</main>
  

{% endblock contenido %}

blog/templates/t_contacto.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} CONTACTO {% endblock titulo %}

{% block contenido %}
<body >
    <section class="contacto">
       <h1 class="title">CONTACTO</h1>
       <p class="contacto-texto2">¿Querés comunicarte con nosotros?</p>
        <section>
            <div class="redes">
                <div class="instagram">
                    <img src="{% static 'img/redes2.png'%}" width="30px" alt="Instagram">
                    <a href="https://www.instagram.com/fundacion__amigos/" target="_blank">INSTAGRAM</a>
                </div>
                <div class="facebook">
                    <img src="{% static 'img/redes1.png'%}" width="30px" alt="Facebook">
                    <a href="https://www.facebook.com/EscultoresenelImpenetrable" target="_blank">FACEBOOK</a>
                </div>
                <div class="correo">
                    <img src="{% static 'img/redes3.png'%}" width="30px" alt="Correo">
                    <a href="mailto:info@amigosdelarteyturismo.org" target="_blank">CORREO</a>
                </div>
                <div>
                    <img src="{% static 'img/redes5.png'%}" width="30px" alt="Ubicacion">
                    <a href="https://goo.gl/maps/16yEVpXTGKqMwufC8" target="_blank">UBICACION</a>
                </div>                
            </div>
            <section class="mapa">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d896.9209838284005!2d-60.6207856!3d-25.9456008!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94404cfba5224f0b%3A0xbe1797f5f1777f83!2sFundaci%C3%B3n%20Amigos%20del%20Arte%20y%20Turismo!5e0!3m2!1ses!2sar!4v1670259373719!5m2!1ses!2sar" width="600" height="450" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </section>
        </section>
    </section>
</body>
{% endblock contenido %}

blog/templates/t_home.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} INICIO {% endblock titulo %}

{% block contenido %}
<body>
  <header>
    <section class="foto-portada">
      <h1 class="title">BIENVENIDOS</h1>
    </section>
  </header>
  <br>
  <br>
  <article class="integrante">
    <h2>La Fundación Amigos del Arte y Turismo:</h2>
  </article>
  <br>
    <p>
      Es una Entidad no lucrativa, con el fin de vincular las expresiones culturales de la región, 
      la idiosincrasia de la gente y el turismo a través del ARTE.
    </p>
    <p>
      Nuestra meta es promover el Arte y el Turismo, rescatando, revalorizando e incluyendo todas las manifestaciones artísticas y 
      culturales, en salvaguarda de nuestra identidad, y en defensa del medio ambiente.
    </p>
    <p>
      Estamos ubicados en el Departamento General Güemes de la provincia del Chaco, en la Puerta del Impenetrable, con una comunidad 
      integrada por pueblos originarios de distintas etnias, criollos y descendientes de inmigrantes de distintos países de Europa.
    </p>
    <p>
      Nos reconocemos como parte de “El Impenetrable”, su cultura y su gente. Por eso, buscamos dar a conocer nuestra región, su 
      riqueza, sus leyendas, su arte y su poesía, que invitan a recorrer lugares como la FIDELIDAD, MISIÓN NUEVA POMPEYA, LA CANGAYÉ, 
      LAS RUINAS DEL Km 71 que nos hablan de nuestra historia y nuestra gente.
    </p>
</body>

{% endblock contenido %}



<!--<img src="{% static 'img/header.jpg' %}"  alt="foto_fundacion" class="foto"> -->

blog/templates/t_nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} NOSOTROS {% endblock titulo %}

{% block contenido %}

<body>
  <main class="ppal">
    <section class="cont-nosotros">
        <h2 class="title"> ¿Quienes somos?</h2>
    </section>
  </main>
  <section class="patrimonio">
  <article class="integrante">
    <h2>PRESENTACIÓN Fundación Amigos del Arte y Turismo</h2>
  </article>
    <br>
    <p>La Fundación tiene su origen en la Inauguración del Hotel Portal del Impenetrable el 29 de septiembre de 2012, acontecimiento en el que se reunieron el Dr. Alfredo Lázara Valdéz (propietario del hotel), el Dr Oscar Alberto Nievas (Intendente de Castelli) y Fabriciano Gómez (presidente de la Fundación Urunday y autor de la obra “El Portal del Impenetrable”). En ese acto Fabriciano propone la idea de organizar un encuentro de escultores en la Plaza San Martín, en junio de 2013. Desde el año 2012, contamos con el apoyo, asesoramiento y acompañamiento de la Fundación Urunday, principalmente en la persona de Fabriciano Gómez.
      
      El 1º de marzo de 2015 quedó formalmente constituida la Fundación Amigos del Arte y Turismo, con la siguiente conformación del consejo: 
      <ul>
        <li>• Presidente: Dr. Alfredo Lázara Valdéz</li>
        <li>• Vicepresidente: DG René Bertolucci</li>
        <li>• Secretaria: Prof. Elena Díaz de Lázara</li>
        <li>• Tesorera: Arq. Yolanda M. Rausch</li>
        <li>• Vocal: Dr. Jorge Kleisinger</li>
      </ul>
    </p>
    <p>La Fundación Amigos del Arte y Turismo, con Personería Jurídica Nº452/14 es una Entidad no lucrativa, con el fin de vincular las expresiones culturales de la región, la idiosincrasia de la gente y el turismo a través del ARTE.
    </p>
  </article>
  </section>

  <section class="patrimonio">
  <article class="integrante">
    <h2>MISIÓN</h2>
  </article>
    <br>  
    <p>Ser partícipes del desarrollo cultural, brindar oportunidades y capacitación del Arte y hacer del mismo un atractivo turístico.</p>
  
  </section>

  <section class="patrimonio">
  <article class="integrante">
    <h2>VISIÓN</h2>
  </article>
    <br>    
    <p>Sacar a la luz lo que late en el Impenetrable. </p>
  </article>
  </section>

  <section class="patrimonio">
  <article class="integrante">
    <h2>OBJETIVOS GENERALES</h2>
  </article>
    <br>  
    <p>
      • Velar por nuestro rico patrimonio cultural y dar a conocer a todos los que nos visiten las diferentes expresiones de nuestra identidad.<br>
      • Estimular y divulgar el arte y el turismo y fomentarlos como fuente de superación de las personas de nuestra comunidad y darlo a conocer.<br>
    </p>
  </article>
  </section>

  <section class="patrimonio">

  <article class="integrante">
    <h2>OBJETIVOS ESPECÍFICOS</h2>
  </article>
    <br>
    <p>
      • Organizar eventos de cualquier naturaleza con carácter regional, nacional e internacional en pro del desarrollo del arte y el turismo.<br>
      • Impulsar el turismo revitalizando las artes tradicionales y la industria artesanal de la zona a través de la comercialización de los productos locales y de otros recursos de aquellas localidades marginadas por la desindustrialización o el aislamiento.<br>
      • Proteger y restaurar nuestro patrimonio cultural y artístico.<br>
      • Organizar encuentros culturales, espectáculos y otros acontecimientos que contribuyan a divulgar nuestra idiosincrasia.<br>
      • Desarrollar programas de formación y capacitación que estén íntimamente relacionados con la misión de la fundación.<br>
      • Generar muestras públicas de contemplación de técnicas y observación de creación de obras artísticas celebrando exposiciones temáticas con artistas invitados.<br>
      • Ayudar y colaborar en proyectos públicos o privados en los que se combinen cultura y turismo (rutas literarias, rutas históricas, etc.) con mayor intensidad en lo que se refiere a la colaboración recíproca con otras Fundaciones culturales o de otros fines que coadyuven en la promoción de la cultura.<br>
      • Apoyar proyectos educativos, culturales destinados a destacar la importancia de la cultura.<br>
      • Desarrollar e impulsar el turismo interior en el Impenetrable en sintonía con la tendencia en alza del turismo alternativo (cultura y naturaleza).<br>
      • Promover actividades de formación en el conocimiento de la cultura.<br>
      • Potenciar Castelli y su región como destino turístico.<br>

    </p>
  </article>
  </section>

  <article class="integrante">
      <h2>INTEGRANTES DE LA COMISION ACTUAL</h2>
  </article>

  <section class="galerias">
    <div class="galeria">
      <img src="{% static 'img/presidente.jpg' %}" alt="foto_presidente" >
      <h5 class="nombre">Presidente: DG. Rene Bertolucci</h5>
    </div>

    <div class="galeria">
      <img src="{% static 'img/vicepresidente.jpg' %}"  alt="foto_vicepresidente">
      <h5 class="nombre">Vicepresidente: Arq. Yolanda M. Rausch</h5>
    </div>

    <div class="galeria">
        <img src="{% static 'img/secretaria.jpg' %}"  alt="foto_secretaria">
      <h5 class="nombre">Secretaria: Prof. Marisa Santamaría</h5>
    </div>

    <div class="galeria">
        <img src="{% static 'img/tesorera1.jpg' %}"  alt="foto_tesorera">
      <h5 class="nombre">Tesorera: Prof. Elena Díaz de Lázara</h5>
    </div>

    <div class="galeria">
      <img src="{% static 'img/vocal.jpg' %}"  alt="foto_vocal"  alt="foto_tesorera">
      <h5 class="nombre">Vocal: Dr. Jorge Kleisinger</h5>
    </div>

  </section>
<br>
<br>
  <section class="patrimonio">
    <article class="integrante">
    
      <h2>RECUPERACIÓN DE PATRIMONIO HISTÓRICO:</h2>
    </article>
      <br>
      <p>En febrero de 2015, la Municipalidad de Juan José Castelli nos cedió en comodato el antiguo edificio de la primera escuela primaria de la ciudad, la Escuela Nacional Nº 255. A partir de ese momento comenzamos a elaborar el proyecto de recuperación del mismo. 
        Luego del Encuentro de 2015, comenzaron las obras de la primera etapa, con la colaboración del Municipio con los materiales, y la Fundación aportó la mano de obra.
        El 7 de julio de 2016 se inauguró la 1º etapa de la obra, tres aulas y un sanitario. El edificio ahora funciona como sede de nuestra Fundación.
      </p>
    </article>
  </section>
  
  <section class="patrimonio">
  <article class="integrante">
    <h2>RESEÑA DE LOS ENCUENTROS ANTERIORES:</h2>
  </article> 
    <br> 
    <p>
      2013: Encuentro de Escultores del Impenetrable: “Especies en Extinción” – 17 al 22 de junio 2013. Material: madera de palo santo.<br>
      2014: Encuentro de Escultores del Impenetrable: “Guardianes del Monte” – 27 de octubre al 1 de noviembre de 2014. Material: cerámica.<br>
      2015: Encuentro de Escultores en el Impenetrable:” Mitos y Leyendas”4 al 11 de junio de 2015. Material: Madera de Palo Santo.<br>
      2016: Encuentro Internacional de Escultores en el Impenetrable 2016: “Sonidos del Monte” del 26 al 31 de julio de 2016. Material: Mármol, acero y Palo Santo.<br>
      2017: Encuentro de escultores en el Impenetrable 2017: “El origen” – 10 al 15 de julio de 2017. Material: madera de Palo Santo.<br>
      2018: Encuentro Internacional de Escultores en el Impenetrable 2018: “Fuerza Natural” del 24 al 28 de julio. Material: Mármol, acero y Palo Santo.<br>
      2019: Encuentro de Escultores en el Impenetrable 2019: “Instinto” del 25 al 30 de junio. Material: Palo Santo <br>
    </p>
  </article>
</section>

</body>  
{% endblock contenido %}

blog/templates/usuarios/login.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} INICIO SESION {% endblock titulo %}
{% block contenido %}

<body >
	<section class="patrimonio">
		<article>
       		<h1 class="title">INICIO DE SESION</h1>
		</article>
		<article class="integrante">
            <h2 class="contacto-texto2">Te invitamos ser parte de nuestra comunidad</h2>
        </article>

            <p> Registrandote podras recibir nuestras novedades e invitaciones a los eventos de la organización.</p>
		<div class="iniciosesion">
			<form method="POST" class="login">{%csrf_token%}
				{{form.errors}}
				<input type="text" name="username" placeholder="USUARIO" class="usuario">
				<input type="password" name="password" placeholder="PASSWORD" class="contrasena">

				<input type="submit" name="" value="ENVIAR" class="btn">

			</form>
		</div>

	</section>
</body>

{% endblock %}

blog/templates/usuarios/registro.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} REGISTRO {% endblock titulo %}

{% block contenido %}
<body>
  <section class="registro">

    <main role="main">
      <div class="container">
        <div class="row mt-3">
          <div class="col-md-9 mx-auto mb-5">
            <form action="" method="post">{% csrf_token %}         
              <h3 class="title">Registro</h3>
              {{form.as_p}}
              <p><input type="submit" class="btn btn-primary btn-block" value="Confirmar"></p>
            </form>
          </div>
        </div>
      </div>
    </main>
  </section>  
</body>
<br>
<br>
{% endblock contenido %}